version: '3.7'
services:
  Web:
    image: abiosoft/caddy
    ports:
      - 80:80
    volumes:
      - './Caddyfile:/etc/Caddyfile'
  api:
    build:
      context: './API'
      dockerfile: 'Dockerfile.dev'
    image: 'distributeddns'
    environment:
      DB_HOST: database
      DB_PASSWORD: pgpass
    volumes:
      - './API:/development'
      - './API.graphql:/API.graphql'
  database:
    image: postgres:11-alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    ports:
      - 5859:5432
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: application
volumes:
  databaseData:
